# Test indirect left-recursion: A := B x, B := A y
# This should be transformed to eliminate the cycle

expr := term '+' expr
expr := term

term := factor '*' term  
term := factor

factor := 'x'
factor := 'y'
factor := '(' expr ')'

