# Test mutual left-recursion: A := B alpha, B := C beta, C := A gamma
# Classic cycle that needs elimination

decl := stmt 'end'
decl := 'simple'

stmt := block ';'
stmt := 'statement'

block := decl 'in'
block := 'begin'

