#!/usr/bin/env bash
# G1-A correctness battery (PGEN-RGX-0078-0166) — the standing land protocol.
# Sequential, ONE heavy job at a time, every step memory-guarded at 16384 MB.
set -uo pipefail
R=/Users/richarddje/Documents/github/pgen
S=/private/tmp/claude-501/-Users-richarddje-Documents-github-pgen/ebe196bd-d754-4a06-ae42-207d4a2d6e48/scratchpad/g1a
G="$R/scripts/run_with_memory_guard.sh --budget-mb 16384 --floor-pct 10 --timeout-s 7200"
overall=0
rm -f "$S/battery_failures.txt"

step() {
  local name="$1"; shift
  echo "=== BATTERY $name: START $(date +%H:%M:%S) ==="
  $G --marker "$S/bat_$name.marker" -- "$@" > "$S/bat_$name.log" 2>&1
  local rc=$?
  echo "=== BATTERY $name: done exit=$rc $(date +%H:%M:%S) ==="
  if [ $rc -ne 0 ]; then overall=1; echo "FAILED: $name" >> "$S/battery_failures.txt"; fi
}

# A. Dual-feature ast_pipeline rebuild FIRST — the #140-class vintage trap:
#    the focus_* train just overwrote target/debug/ast_pipeline single-feature.
step dualbuild bash -c "cd $R/rust && cargo build --features 'generated_parsers ebnf_dual_run' --bin ast_pipeline"

# B. Debug probe rebuilt at the final artifact vintage (the -0157 vintage rule).
step probe_rebuild bash -c "cd $R/rust && cargo build --features generated_parsers --bin parseability_probe"

# C. Full dual-feature lib suite — carries the ALL-11 differential-equivalence
#    gate (interpreter <-> generated byte-identical), the decisive value oracle.
step libsuite bash -c "cd $R/rust && cargo test --features 'generated_parsers ebnf_dual_run' --lib"

# D. Regex certificate coverage, seeds 0/7/42 (banked: 268/9/259/0 fully_certified).
step cert bash -c "cd $R/rust && for s in 0 7 42; do ./target/debug/ast_pipeline ../grammars/regex.ebnf --report-certificate-coverage --entry-rule regex --count 40 --seed \$s 2>&1 | grep -E 'CERTIFICATE-COVERAGE|single_path_fallback'; done"

# E-I. The make gates.
step ast_shape_contract_gate       make -C "$R/rust" SHELL=/bin/bash ast_shape_contract_gate
step duality_hunt_gate             make -C "$R/rust" SHELL=/bin/bash duality_hunt_gate
step regex_pcre2_compile_oracle_gate make -C "$R/rust" SHELL=/bin/bash regex_pcre2_compile_oracle_gate
step regex_typed_differential_gate make -C "$R/rust" SHELL=/bin/bash regex_typed_differential_gate
step clippy_on_rust_change         make -C "$R/rust" SHELL=/bin/bash clippy_on_rust_change

echo "BATTERY COMPLETE overall=$overall"
[ -f "$S/battery_failures.txt" ] && cat "$S/battery_failures.txt"
exit $overall
