#!/usr/bin/env bash
# stimuli/run_external_corpus.sh <sv|vhdl> [per_file_timeout_s] [jobs] [max_files]
#
# EXTERNAL-CORPUS.3.1 / .3.2 — bulk characterization of the external TEST CORPORA
# vendored under stimuli/<fam>/subs/ (git submodules, sparse-checked-out to their
# test dirs). Parses EVERY corpus file with the PGEN parser and tallies
# parse-pass / parse-fail / timeout per sub-corpus, then writes a dated
# characterization report.
#
# Doctrine (characterize, don't game — EXTERNAL-CORPUS / project_external_corpus_doctrine):
#   - The number reported is the HONEST raw parse outcome, not a forced "conformance pass".
#   - Many corpus files are INTENTIONALLY invalid (e.g. GHDL `gna` bug-regressions,
#     VESTS `non_compliant/`, sv-tests files with `:should_fail_because:`), so a
#     parse-FAIL is often the CORRECT outcome, not a parser bug. This runner reports
#     raw outcomes per sub-corpus; deeper expected-vs-actual adjudication is a follow-up.
#   - These corpora exercise the FULL grammars (not simplified subsets), so genuine
#     divergences are real parser gaps — a bug-finding oracle.
#
# Usage:
#   stimuli/run_external_corpus.sh sv            # all SV corpora, 20s/file, 8 jobs
#   stimuli/run_external_corpus.sh vhdl 30 6     # VHDL, 30s/file, 6 jobs
#   stimuli/run_external_corpus.sh sv 20 8 500   # cap at 500 files (smoke)
set -uo pipefail

FAM="${1:?usage: run_external_corpus.sh <sv|vhdl> [timeout_s] [jobs] [max_files]}"
TIMEOUT_S="${2:-20}"
JOBS="${3:-8}"
MAX_FILES="${4:-0}"   # 0 = no cap

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROBE="${PGEN_PARSE_PROBE_BIN:-$ROOT/rust/target/debug/parseability_probe}"

ROOT_EARLY="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
case "$FAM" in
  sv)   GRAMMAR=systemverilog; export PROFILE_ARGS="--profile sv_2017";
        FIND_EXTS=( -name '*.sv' -o -name '*.svh' -o -name '*.v' );
        # SV-CORPUS-GRAD.8: fold the pre-submodule-vintage uvm-core vendoring
        # (plain tracked files) into the bulk universe as sub-corpus `uvm-core`.
        EXTRA_DIRS=( "$ROOT_EARLY/stimuli/sv/uvm" );;
  vhdl) GRAMMAR=vhdl;          export PROFILE_ARGS="";
        FIND_EXTS=( -name '*.vhd' -o -name '*.vhdl' );
        EXTRA_DIRS=();;
  *) echo "unknown family '$FAM' (expected sv|vhdl)" >&2; exit 2;;
esac

[ -x "$PROBE" ] || { echo "parseability_probe not found/executable at $PROBE" >&2; exit 3; }

SUBS="$ROOT/stimuli/$FAM/subs"
OUTDIR="$ROOT/stimuli/$FAM/characterization"
mkdir -p "$OUTDIR"
RESULTS="$OUTDIR/results.tsv"
REPORT="$OUTDIR/characterization.md"
: > "$RESULTS"

export PROBE GRAMMAR TIMEOUT_S

# Parse a single file; emit "<subcorpus>\t<status>\t<path>".
parse_one() {
  local f="$1" sub rc status
  sub="$(printf '%s' "$f" | sed -E 's#.*/subs/([^/]+)/.*#\1#; s#.*/stimuli/sv/uvm/.*#uvm-core#')"
  # shellcheck disable=SC2086
  timeout "$TIMEOUT_S" "$PROBE" --parse "$GRAMMAR" "$f" $PROFILE_ARGS >/dev/null 2>&1
  rc=$?
  if [ "$rc" -eq 0 ]; then status=pass
  elif [ "$rc" -eq 124 ]; then status=timeout
  else status=fail; fi
  printf '%s\t%s\t%s\n' "$sub" "$status" "$f"
}
export -f parse_one

echo "external-corpus[$FAM]: collecting files under $SUBS ..." >&2
mapfile -t FILES < <(find "$SUBS" ${EXTRA_DIRS[@]+"${EXTRA_DIRS[@]}"} -type f \( "${FIND_EXTS[@]}" \) 2>/dev/null | sort)
TOTAL_FOUND=${#FILES[@]}
if [ "$MAX_FILES" -gt 0 ] && [ "$TOTAL_FOUND" -gt "$MAX_FILES" ]; then
  FILES=( "${FILES[@]:0:$MAX_FILES}" )
  echo "external-corpus[$FAM]: capping at $MAX_FILES of $TOTAL_FOUND files (smoke run)" >&2
fi
echo "external-corpus[$FAM]: parsing ${#FILES[@]} files (timeout=${TIMEOUT_S}s, jobs=$JOBS) ..." >&2

printf '%s\0' "${FILES[@]}" | xargs -0 -P "$JOBS" -I{} bash -c 'parse_one "$@"' _ {} >> "$RESULTS"

# ---- aggregate ----
TOTAL=$(wc -l < "$RESULTS" | tr -d ' ')
PASS=$(awk -F'\t' '$2=="pass"' "$RESULTS" | wc -l | tr -d ' ')
FAIL=$(awk -F'\t' '$2=="fail"' "$RESULTS" | wc -l | tr -d ' ')
TMO=$(awk -F'\t' '$2=="timeout"' "$RESULTS" | wc -l | tr -d ' ')
PCT=$(awk -v p="$PASS" -v t="$TOTAL" 'BEGIN{ if(t>0) printf "%.1f", 100*p/t; else print "0.0" }')

{
  echo "# External Test-Corpus Characterization — \`$FAM\` (EXTERNAL-CORPUS.3.$([ "$FAM" = sv ] && echo 1 || echo 2))"
  echo
  echo "Generated by \`stimuli/run_external_corpus.sh $FAM $TIMEOUT_S $JOBS $MAX_FILES\` against \`$(basename "$PROBE")\`."
  echo "Per-file parse via \`parseability_probe --parse $GRAMMAR <file> $PROFILE_ARGS\`, timeout ${TIMEOUT_S}s, $JOBS-way parallel."
  echo
  echo "> **Characterize, don't game.** Raw parse outcomes only. Many corpus files are"
  echo "> INTENTIONALLY invalid (GHDL \`gna\` regressions, VESTS \`non_compliant/\`, sv-tests"
  echo "> \`:should_fail_because:\`), so a parse-FAIL is frequently the CORRECT outcome — not a"
  echo "> parser bug. Expected-vs-actual adjudication per sub-corpus is the follow-up slice."
  echo
  echo "## Totals"
  echo
  echo "| files parsed | pass | fail | timeout | pass-rate |"
  echo "|---|---|---|---|---|"
  echo "| $TOTAL | $PASS | $FAIL | $TMO | ${PCT}% |"
  echo
  echo "## Per sub-corpus"
  echo
  echo "| sub-corpus | files | pass | fail | timeout | pass-rate |"
  echo "|---|---|---|---|---|---|"
  awk -F'\t' '
    { tot[$1]++; if($2=="pass")p[$1]++; else if($2=="timeout")to[$1]++; else f[$1]++ }
    END { for (s in tot) {
            r = (tot[s]>0)? 100*p[s]/tot[s] : 0;
            printf "| %s | %d | %d | %d | %d | %.1f%% |\n", s, tot[s], p[s]+0, f[s]+0, to[s]+0, r
          } }
  ' "$RESULTS" | sort
  echo
  echo "_Raw per-file results: \`stimuli/$FAM/characterization/results.tsv\`._"
} > "$REPORT"

echo "external-corpus[$FAM]: $TOTAL parsed — pass=$PASS fail=$FAIL timeout=$TMO (${PCT}% pass). Report: $REPORT" >&2
