(regexps
 (timing_path_re   "\bpath\s+\d+\s*:(?s:.+?)(?=\bpath\s+\d+\s*:|$)")
 (se_clock_re      "\(clock\s+(\S+?)\).+?([a-z]+).+?\s(R|F)")
 (se_point_re      "(Start|End)-point\s+:\s+(\S+)")
 (slack_re         "Timing\s+slack\s+:.+?(-?\d+(\.\d+)?)")
 (timing_data_re   "(?s)-{50,}(.+?)-{50,}")
 (path_type_re     "\s+setup\s+|\s+ext\s+delay\s+\+")
)

(rise_o_fall
 (R  rise)  
 (F  fall) 
)
