(gp_id_key_list  split pathcount engine file path_index)
(gf_id_key_list  file .)
(sepc            .)

(gf_enscript_extensions  
 ("\.(v)$"                     1)
 ("\.(vhd)l?$"                 1)
 ("\.(tcl|sgdc|do)$"           1)
 ("\.(pm|pl|cgi|plg)$"         1)
 ("\.(ts|conf|tk)$"            1)

 ("\.(sh|ksh|bash|zsh|tcsh)$"  1)

; Should be removed
 ("\.(sve)$"  1)
)

(lang
 (v    verilog)
 (vhd  vhdl)
 (tcl  tcl)
 (do   tcl)
 (sgdc tcl) ; spyglass contraints' files
 (pl   perl)
 (pm   perl)
 (cgi  perl)
 (plg  perl)
 (ts   elisp)
 (conf elisp)
 (tk   elisp)
 (csh  sh)
 (sh   sh)
 (tcsh sh)
 (zsh  sh)
 (bash sh)


; Should be removed
; (sve bash)
)

;====================================================
; Should not be read as part of 
; HUtils::Conf or
; HUtils::Read
;====================================================
;(extension_action
; "\.(pdf)$"        (content (type application/pdf)               (plugin  gf_generic_handler))                  
; "\.(xls)$"        (content (type application/vnd.ms-excel)      (plugin  gf_generic_handler))                  
; "\.(ppt)$"        (content (type application/vnd.ms-powerpoint) (plugin  gf_generic_handler))                  
;  \.(?:flt|clt)$"  (content (type text/html)                     (plugin  gf_filelist_handler))
;                   (content (type application/octet-stream)      (plugin  gf_generic_handler))
;)
