
(skew_sequence    by_pathtype sort_for_dutycycled)
(by_pathtype      [seto://stan_backend/by_pathtype])

(sort_for_dutycycled
  (USBOTGFS
   (RECEIVE
    (FSUSB0_DAT
     (fsusb0_dat 
      (rise  {reportfile =~ /USBOTGFS.rpt$/ && startpoint =~ /fsusb0_dat/ && startpoint_edge =~ /r/})
      (fall  {reportfile =~ /USBOTGFS.rpt$/ && startpoint =~ /fsusb0_dat/ && startpoint_edge =~ /f/})
     )
    )

    (FSUSB0_RCV
     (fsusb0_rcv
       (rise  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_rcv/ && startpoint =~ /fsusb0_rcv/ && startpoint_edge =~ /r/})
       (fall  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_rcv/ && startpoint =~ /fsusb0_rcv/ && startpoint_edge =~ /f/})
     )
    )

    (FSUSB0_SE0
     (fsusb0_txen_or_se0
       (rise  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_se0/ && (startpoint =~ /fsusb0_txen/ || startpoint =~ /fsusb0_se0/) && startpoint_edge =~ /r/})
       (fall  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_se0/ && (startpoint =~ /fsusb0_txen/ || startpoint =~ /fsusb0_se0/) && startpoint_edge =~ /f/})
     )
    )
   )


   (TRANSMIT
    (FSUSB0_DAT
     (fsusb0_dat 
      (rise  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_dat/ && endpoint =~ /fsusb0_dat/ && endpoint_edge =~ /r/})
      (fall  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_dat/ && endpoint =~ /fsusb0_dat/ && endpoint_edge =~ /f/})
     )
    )

    (FSUSB0_TXEN
     (fsusb0_se0_or_txen
       (rise  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_txen/ && (endpoint =~ /fsusb0_se0/ || endpoint =~ /fsusb0_txen/) && endpoint_edge =~ /r/})
       (fall  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_txen/ && (endpoint =~ /fsusb0_se0/ || endpoint =~ /fsusb0_txen/) && endpoint_edge =~ /f/})
     )
    )

    (FSUSB0_SE0
     (fsusb0_txen_or_se0
       (rise  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_se0/ && (endpoint =~ /fsusb0_txen/ || endpoint =~ /fsusb0_se0/) && endpoint_edge =~ /r/})
       (fall  {reportfile =~ /USBOTGFS.rpt$/ && first_arrow_point =~ /fsusb0_se0/ && (endpoint =~ /fsusb0_txen/ || endpoint =~ /fsusb0_se0/) && endpoint_edge =~ /f/})
     )
    )
   )

   ;(set2
   ;)
  )

  ;(INTERFACE2
  ;)

  ;(INTERFACE3
  ;)
)

; When provided the "reference_tables" parameter implies ALGO#2
; It should be used to select between ALGO#1 and ALGO#2
(what_to_check
 ; w/ ALGO#2
 (transmit  (path_tables      USBOTGFS.*TRANSMIT) 
            (reference_tables "USBOTGFS.*TRANSMIT.*FSUSB0_TXEN.*fall") 
	    (exclude_tables   "USBOTGFS.*TRANSMIT.*FSUSB0_TXEN.*rise")
	    (max_skew  1000)
 )

 ; w/ ALGO#1
 (receive   (path_tables USBOTGFS.*RECEIVE) (max_skew 1000))

 ; w/ ALGO#2
 ;(transmit_fwref (path_tables USBOTGFS.*TRANSMIT) (reference_tables  "fsusb0_se0.*rise") (max_skew 1000))
)


