(regexps
 (timing_path_re   "\bPath\s+\d+\s*:(?s:.+?)(?=\bPath\s+\d+\s*:|$)")
 (se_clock_re      "(Begin|End)point\s*:.+?\s+(leading|trailing)\s+edge\s+of\s+'(\w+)'")
 (se_point_re      "(Begin|End)point\s*:\s+(\S+)")
 (slack_re         "\s+Slack\s+Time\s+(-?\d+(\.\d+)?)")
 (timing_data_re   "(?s)-{50,}(.+?)-{50,}")
 (path_type_re     "\sSetup\s+Check\s|^\+\s+Setup\s")
)

(rise_o_fall
 (leading   rise)  
 (trailing  fall) 
)

(start_o_end
 (End    end)  
 (Begin  start) 
)
