(author_signame  QDJERIC)
(author_name     "Richard DJE")

(wen_prefix  dtwen)
(state_variable  sv)
(output_port_suffix _strb)
(state_type_name  statetype)
(constant_suffix  _c)

(non_standard_type_re "dft_.+_t|\w+_mem_(?:in|out)_t")

; Turning MERGE OFF by default
(merge  0)

(context_clause 

{LIBRARY IEEE;
USE     IEEE.STD_LOGIC_1164.ALL;
USE     IEEE.STD_LOGIC_UNSIGNED.ALL;

})

(add_package_re  "([[:alpha:]]\w+)(?:\.((?1)))?$")

(sharedinfo  "^\+(?:size|default|init|system)$")

(block_prefix              "")

(default_clock_name        clk   )
(default_async_reset_name  rst_n )
(architecture_name_suffix  _rtl_a)
(architecture_name         rtl   )
(entity_name_suffix        _e    )
(merge_name_suffix         _ea   )
(instance_label_prefix     a_    )
(vhdl_file_suffix          vhd   )

;(_dp              fsm_common_dp)
(_top              fsm_top_level)
(output_directory  components)
(_testop
 (=  _eq_)
 (!= _ne_)
 (>= _ge_)
 (>  _gt_)
 (<= _le_)
 (<  _lt_)
)

(_negated_op
 (= !=)
 (!= =)
 (>= <)
 (<  >=)
 (<= >)
 (>  <=)
)

(_assign_firstre "(?i)<(!)?([a-z]\w*(?:\[\d+(?::\d+)?\])?)((?:!?=|>=?|<=?)(?:(?:\d+'x?)?[0-9a-f]+|(?:[a-zA-Z]\w*(?:\[(\d+)(?::(\d+))?\])?)))?")

(_logicalnode_leaf_re {^(?ix)(!)?(?:([a-z]\w*)(?:\[(\d+)(?::(\d+))?\])?) (?:(?<TESTOP>!?=|>=?|<=?) (?: (?:(?<SIZE>\d+)'(?<BASE>x)?(?<TESTEDCONSTANT>[0-9a-f]+))  | 
												       (?<TESTEDCONSTANT>[01]+)                                  |
											               (?<ASIGNAL>[a-zA-Z]\w*) (?:\[(?<HIDX>\d+)(?::(?<LIDX>\d+))?\])?
											           )
			                                                 )?  $})

(_template_dir  TEMPLATE)
(_literal_constant_re "(?i:[01]+|\d+'x?[0-9a-f]+)")
(_relationalop_re "(?:!?=|>=?|<=?)")

(testnode_scv_wv_re      "^<!?[a-z]\w*(?:\[\d+(?::\d+)?\])?(?:!?=|>=?|<=?)\S+$")
(testnode_scv_wv_re_cap  "<(!)?([a-z]\w*(?:\[\d+(?::\d+)?\])?)(!?=|>=?|<=?)(\S+)")


(entity_file_name_template        "<module_name><entity_name_suffix>.<vhdl_file_suffix>")
(architecture_file_name_template  "<module_name><architecture_name_suffix>.<vhdl_file_suffix>")

(register_process_template_w_asyncreset     {
-- <comment> register assignment
<label> : PROCESS (<clock>, <asreset>)
BEGIN
 IF <asreset> = '0' THEN
   <register>  <= <reset_value>;
 ELSIF RISING_EDGE(<clock>) THEN
   <register>  <= <next_value>;
 END IF;
END PROCESS <label>;
})
