(top             /vobs/z1s1dev/common/design)

(_unmapped       form_ver/run/report_unmapped_points.log)
(_synt_log       synt/asic/reports/*_synthesis.log)
(_hierarchy_map  synt/asic/reports/*_hierarchy_uniquify.rep)


(re
  (processing    "Processing\s+'(\S+?)'")
  (opt_120X      "Information:.+?'(\S+?)'.+?\((OPT-120.)\)")
)

(ure
  (unmaped_point "Unmapped\s+point\s+\((\S+?)(?:\s+(.+?))?\):")
  (keypoint      "\((.)\)\s+\S+\s+(\S+)\s+(\S+)")
)

(cb
  (processing    procb)
  (opt_120X      opt120x_cb)
  (unmaped_point unmaped_point_cb)
  (keypoint      keypoint_cb)
)

(regfield
 (mod   0)
 (path  1)
 (reg   2)
 (optid 3)
)

