(plugin_conf
 (clockmatrix   stan_backend)
 (defaultout    stan_backend)
 (filterout     stan_backend)
 (eponsout      stan_backend)
 (syncts        stan_backend)
 (interface     stan_backend)

 (quick_dft     stan_backend)
 (treeout       stan_backend)
 (skew          skew)
 (dutycycled    dutycycled)

 (old_default   stan_old)
 (dm_measures   stan_dm_measures)

 (sdcgen        sdcgen)

 (network       network)
 (netw_fi       network)
 (reset_analyze network)

 ;(wrap_upd      none)
 ;(wrape_upd     none)
 ;(wrapa_upd     none)
 ;(raw           none)
 ;(seview        none)
 ;(mytest        none)

 (nlc             nlc)
)

