(format
 (libview_library     (bg_color purple)  (align center))
 (libview_cell        (bg_color light_green)  (align center))
 (libview_pin         (bg_color orange) (align center))
 (libview_cell_rise   (bg_color light_purple)   (color white) (align center))
 (libview_cell_fall   (bg_color light_blue) (align center))
 (libview_other_group (bg_color yellow) (align center))
 (libview_link        (bg_color blue) (color white) (align center))
)

