(genlist  GEN1H_WCDMA_UDSP_JTAG_TI_D2D_RTCK
          GEN2H_WCDMA_HSDPA_JTAG_TI_D2D_RTCK
          GEN3H_D2D_RTCK
	  GEN4H_WCDMA_MACC_JTAG_TI_D2D_RTCK
	  GEN5H_D2D_RTCK
	  GEN6H_WCDMA_UDSP_JTAG_TI_D2D_RTCK
	  GEN7H_D2D_RTCK
	  GEN8F_WCDMA_UDSP_JTAG_TI_D2D_RTCK
	  GEN9F_WCDMA_HSDPA_JTAG_TI_D2D_RTCK
	  GEN10F_D2D_RTCK
	  GEN11F_WCDMA_MACC_JTAG_TI_D2D_RTCK
	  GEN12F_WCDMA_UDSP_JTAG_TI_D2D_RTCK
	  GEN13F_D2D_RTCK
)

(gendescr
 (GEN1H_WCDMA_UDSP_JTAG_TI_D2D_RTCK  (port d2d_rtck) (source SRC1H_WCDMA_UDSP_JTAG_TI_D2D_RTCK ) (freq 40))
 (GEN2H_WCDMA_HSDPA_JTAG_TI_D2D_RTCK (port d2d_rtck) (source SRC2H_WCDMA_HSDPA_JTAG_TI_D2D_RTCK) (freq 40))
 (GEN3H_D2D_RTCK                     (port d2d_rtck) (source SRC3H_D2D_RTCK                    ) (freq 40))
 (GEN4H_WCDMA_MACC_JTAG_TI_D2D_RTCK  (port d2d_rtck) (source SRC4H_WCDMA_MACC_JTAG_TI_D2D_RTCK ) (freq 40))
 (GEN5H_D2D_RTCK                     (port d2d_rtck) (source SRC5H_D2D_RTCK                    ) (freq 10))
 (GEN6H_WCDMA_UDSP_JTAG_TI_D2D_RTCK  (port d2d_rtck) (source SRC6H_WCDMA_UDSP_JTAG_TI_D2D_RTCK ) (freq 20))
 (GEN7H_D2D_RTCK                     (port d2d_rtck) (source SRC7H_D2D_RTCK                    ) (freq 20))
 (GEN8F_WCDMA_UDSP_JTAG_TI_D2D_RTCK  (port d2d_rtck) (source SRC8F_WCDMA_UDSP_JTAG_TI_D2D_RTCK ) (freq 40))
 (GEN9F_WCDMA_HSDPA_JTAG_TI_D2D_RTCK (port d2d_rtck) (source SRC9F_WCDMA_HSDPA_JTAG_TI_D2D_RTCK) (freq 40))
 (GEN10F_D2D_RTCK                    (port d2d_rtck) (source SRC10F_D2D_RTCK                   ) (freq 40))
 (GEN11F_WCDMA_MACC_JTAG_TI_D2D_RTCK (port d2d_rtck) (source SRC11F_WCDMA_MACC_JTAG_TI_D2D_RTCK) (freq 40))
 (GEN12F_WCDMA_UDSP_JTAG_TI_D2D_RTCK (port d2d_rtck) (source SRC12F_WCDMA_UDSP_JTAG_TI_D2D_RTCK) (freq 20))
 (GEN13F_D2D_RTCK                    (port d2d_rtck) (source SRC13F_D2D_RTCK                   ) (freq 20))
)

(master_list 
  (CRE_SR0	i_neptune3g2_core/emu/U0_SC_EMUN3G2GS60_LOGIC/u0_icepick_arch03_n3g2/u1_icepick/U4_ICEPICK_CLKVOTE/rtck_synch_latch/i0_lab40ybox/Q)
  (CRE_SR1	i_neptune3g2_core/emu/U0_SC_EMUN3G2GS60_LOGIC/u0_icepick_arch03_n3g2/u1_icepick/U4_ICEPICK_CLKVOTE/itck_synch_latch/i0_lab40ybox/Q)
  (GEN_aTCK	i_neptune3g2_core/emu/U0_SC_EMUN3G2GS60_LOGIC/u0_icepick_arch03_n3g2/CLK_SYNC_SKEW_123/Y d2d_tck)
  (GEN_bTCK	i_neptune3g2_core/emu/U0_SC_EMUN3G2GS60_LOGIC/u0_icepick_arch03_n3g2/u1_icepick/U4_ICEPICK_CLKVOTE/ITCK_RTCK_CLK_GATE/i0_icg20_1/CLKOUT d2d_tck)
  (GEN_cTCK	i_neptune3g2_core/emu/U0_SC_EMUN3G2GS60_LOGIC/u0_icepick_arch03_n3g2/u1_icepick/U4_ICEPICK_CLKVOTE/RTCK_RTCK_CLK_GATE/i0_icg20_1/CLKOUT d2d_tck)
)
