(matrix_sequence        by_pathtype  by_pathgroup by_startpoint_clock by_endpoint_clock by_startpoint by_endpoint by_capture_1)
(by_capture_1          (dmpp    group_byRE reportfile "(?i).+/.+?([a-z0-9]+)_([a-z0-9]+)_([a-z0-9]+)_([a-z0-9]+)_([a-z0-9]+)_([a-z0-9]+)/"))

(hcol       0 2 4 6 8 10)
(vcol       0 0)
(capt_cnt   6)
