(QC_MIN                 1   )
(QC_MAX                 2.22)
(QC_FIZZ_MAX            2.22)
(QC_FIZZ_MIN            1   )
(QC_FIZZ_4CORNER_MAX    2.22)
(QC_FIZZ_4CORNER_MIN    1   )
(VBOX_MIN               0.88)
(VBOX_MAX               4.54)
(BURNIN_MIN             0.88)
(BURNIN_MAX             4.54)
(1.3_QC_MAX             2.5 )
(1.3_QC_MIN             1.03)
(1.3_QC_4C_MAX          2.5 )
(1.3_QC_4C_MIN          1.03)
(1.05_QC_MAX_LT         3.7 )
(1.05_QC_MIN            1.46)
(1.05_QC_4C_MAX         3.7 )
(1.05_QC_4C_MIN         1.46)
