(dc_load_cmd  /vobs/emp/asictools/tl_asic_synthesis/dc_load_netlist)
(run_dir        /vobs/z1s1dev/common/design/camisp/synt/asic/run)
(ddc           /vobs/z1s1dev/common/design/camisp/model/gate/asic/camisp.ddc)

(cg_ids_enable      0)
(cg_id_patterns      HS65_LS_CNHLSX17)
;(cg_id_patterns      {HS65_LS_CNHLSX17|HS65_LH_CNOR2X17|HS65_LH_OR2X9})
(show_common_nodes  0)
