(diag_re   "(?i)###\s+(info|error|warning):\s*([A-Z]+\d+(?:\.\d+)?):\s*(.+?)\s*\(netlist(?:fix|check)\)\.")
(diag_captre
  (R0     "library:\s+(\S+).+?cell:\s+(\S+?)\.")
  (R3.2   "port\s+(\S+).+?master\s+(\S+)")
  (R4     "'(\S+?)'.+?cell\s+(\S+)\s+\(.+?cell\s+(\S+)\)")
  (R21.1  "pin\s+'(\S+?)'.+?instance\s+'(\S+?)'\s+\(physical\s+cell\s+(\S+?)\)")
  (R22    "pin\s+'(\S+?)'.+?cell\s+(\S+)\s+\(physical\s+cell\s+(\S+?)\)")
  (R23.2   "'(\S+?)'.+?pin\s+(\S+).+?cell\s+(\S+)")
  (CHK10  "library:\s+(\S+),.+?cell:\s+(\S+)\s*:")
  (CHK29  "library:\s+(\S+),.+?cell:\s+(\S+?)\s*:.+?'(\S+?)'")
  (CHK50  "library:\s+(\S+),.+?cell:\s+(\S+?):.+?'(\S+?)'")
  (CHK52  "library:\s+(\S+),.+?cell:\s+(\S+):\s+instance\s+(\S+).+?forbidden\s+library\s+:\s+(\S+),\s+cell\s+:\s+(\S+)")
  (CHK60  "library:\s+(\S+),.+?cell:\s+(\S+?)\s*:.+?'(\S+?)'")
)

(diag_msg
  (R0     "missing liberty+ attributes on library: <[0]> cell: <[1]>. This causes HDRC rule to fail")
  (R2     "flat net '<NetName>' is driven by several cells : LIST-OF<pin <[0]> of cell <[1]>> ")
  (R3.2   "port <[0]> of master <[1]> has no connections")
  (R4     "output pin '<[0]>' of cell <[1]> (physical cell <[2]>) drives nothing")
  (R21.1  "input or bidirectional pin '<[0]>' of instance '<[1]>' (physical cell <[2]>) has been left unconnected")
  (R22    "Leaf pin '<[0]>' of cell <[1]> (physical cell <[2]>) has no driver")
  (R23.2  "power supply flat net '<[0]>' is connected to output pin <[1]> of cell <[2]>")
  (CHK10  "library: <[0]>, cell: <[1]>: empty cell")
  (CHK29  "library: <[0]>, cell: <[1]> undriven net '<[2]>'")
  (CHK50  "library: <[0]>, cell: <[1]> Top level module output port '<[2]>' shorted to global net (For TOP Level Block)")
  (CHK52  "library: <[0]>, cell: <[1]> instance <[2]> : forbidden library : <[3]>, cell : <[4]> is used")
  (CHK60  "library: <[0]>, cell: <[1]> dangling port: '<[2]>'")
)

(diag_cbx
 (R2  nlc_r2_cb)
)

