(regexps
 (slack_re                 "slack\s+\(\s*(?:VIOLATED|MET).+")
 (unconstrained_re         "\(\s*Path\s+is\s+unconstrained\)")
 (timing_path              "Startpoint:(?s:.+?)(?:<slack_re>|<unconstrained_re>)")
 (startpoint_re            "Startpoint:\s+\S+\s+\(.+\)")
 (endpointinfo_re          "Endpoint:\s+\S+\s+\(.+\)")
 (endpoint_re              "\S+\s+\(\S+\)[^/]+?(?=data arrival time)")
 (pathgroup_re             "Path Group:\s+(\S+)")
 (pathtype_re              "Path Type:\s+(\S+)")
 (tp_descr_start           "-{10,}")
 (input_external_delay_re  "input\s+external\s+delay\s+(\S+)")
 (output_external_delay_re "output\s+external\s+delay\s+(\S+)")
 (data_arrival_time_re     "data\s+arrival\s+time\s+(\S+)")
 (data_required_time_re    "data\s+required\s+time\s+(\S+)")
 (library_sh_time_re       "library\s+(?:setup|hold)\s+time\s+(\S+)")
 (clock_uncertainty_re     "clock\s+uncertainty\s+(\S+)")
 (epclk_info_tail_re       "clock\s+(?:network\s+delay\s+\(.+?\)\s+\d+\.\d+\D+\d+\.\d+|reconvergence|uncertainty)")
 (clock_source_latency_re  "\(\s*source\s+latency\s*\)|clock\s+source\s+latency(?:\D+\d+\.\d+){2,4}")

 (csplit_test_re           Startpoint:)
)


(re_list  
    slack_re                 
    unconstrained_re         
    timing_path              
    startpoint_re            
    endpointinfo_re          
    endpoint_re              
    pathgroup_re             
    pathtype_re              
    tp_descr_start           
    input_external_delay_re  
    output_external_delay_re 
    data_arrival_time_re     
    data_required_time_re    
    library_sh_time_re       
    clock_uncertainty_re     
    epclk_info_tail_re       
    clock_source_latency_re  
)

(md5_enabled  0)
