("(XCEL2HM vs GUIDELINE) Budget Check: Failed"
	"[2] =~ /PITESTBSCCLK/"
)

("(XCEL2HM vs GUIDELINE) Clock Edge Mismatch"
	"[2] =~ /PITESTBSCCLK/"
)

("Timing Arcs ONLY defined in the LIB file, though missing from XCEL2HM"
	"[2] =~ /PISPAREIN\[[01]\]/ && [3] =~ /falling_edge/"
)
