#(preferred_alternatives
# (n	n	e	w	ne	nw)
# (e	e	s	n	se	ne)
# (s	s	w	e	sw	we)
# (w	w	n	s	nw	sw)
# (ne	e 	n	ne)
# (se	e 	s	se)
# (sw	w 	s	sw)
# (nw	w 	n	nw)
#)

(full_alternatives
 (n	n	e	w	ne	nw	s	sw	se)
 (e	e	s	n	se	ne	w	sw	nw)
 (s	s	w	e	sw	se	n	nw	ne)
 (w	w	n	s	nw	sw	e	ne	se)
 (ne	e 	n	ne	s	se	w	sw	nw)
 (se	e 	s	se	w	sw	ne	n	nw)
 (sw	w 	s	sw	e	se	nw	n	ne)
 (nw	w 	n	nw	s	sw	e	se	ne)
)

#(limited_alternatives
# (n	n	e	w	ne	nw)
# (e	e	s	n	se	ne)
# (s	s	w	e	sw	se)
# (w	w	n	s	nw	sw)
# (ne	e 	n	ne	s	se)
# (se	e 	s	se	w	sw)
# (sw	w 	s	sw	e	se)
# (nw	w 	n	nw	s	sw)
#)
#(limited_alternatives
# (n	n	e	w	ne	nw)
# (e	e	s	n	se	ne)
# (s	s	w	e	sw	se)
# (w	w	n	s	nw	sw)
# (ne	e 	n	ne	s	se)
# (se	e 	s	se	n	ne)
# (sw	w 	s	sw	n	nw)
# (nw	w 	n	nw	s	sw)
#)

(limited_alternatives
# How did we arrive here ? / which direction are we going to take ?
 (n  (n  n e  w)
     (w  w n)
     (e  e n)
     (nw w n nw)
     (ne e n ne)
     (se e n)
     (sw w n)
 )
 
 (e  (e   e  n  s)
     (n   n  e)
     (s   s  e)
     (se  e  s  se)
     (sw  s  e)
     (ne  n  e  ne)
     (nw  n  e)
 )

 (s  (e   e  s)
     (s   s  e  w)
     (w   w  s)
     (ne  e  s)
     (se  e  s  se)
     (sw  w  s  sw)
     (nw  w  s)
 )
 
 (w  (w  w n  s)
     (s  s w)
     (n  n w)
     (sw s w sw)
     (se s w)
     (ne n w)
     (nw n w nw)
 )
 
 (ne (ne ne n e  se nw) 
     (n  n  w nw  e  ne)
     (nw nw n  e  ne)
     (e  e  ne se n s)
     (se se e ne n nw)
 )
 
 (se  (se se s e ne sw) 
      (e  e  ne  se  s  sw)
      (s  s  se  sw  e  ne)
      (ne ne e  se  s  sw)
 )
 
 (sw  )
 
 (nw  )
)
