(port_key2col
 (name       0)
 (direction  1)
 (type       2)
 (msi        3)
 (lsi        4)
 (force      5)
)

(signal_key2col
 (name       0)
 (type       1)
 (msi        2)
 (lsi        3)
)

(std_context_clause   {
LIBRARY IEEE;
USE     IEEE.STD_LOGIC_1164.ALL;
})

