(sections
 (setup_hold_tmax_tmin      	"=setup_hold_tmax_tmin="   	"=setup_hold_tmax_tmin_end=" 	"\s+")
)

(scripts
 (setup_hold_tmax_tmin
  (if (eval {$_ROW_ == 0})
   (then
    (write (3 3) white_on_black_bold)
    (write (4 4) white_on_black_bold)
    (write (5 5) white_on_black_bold)
   )
   
   (if (eval {$_ROW_ == 1}) 
    (then
     (write_force (0 " ") dark_violet1)
     (write (1 1) path_type)
     (write_force (2 " ") dark_violet1)
     (write (3 3) voltage)
     (write (4 4) voltage)
     (write (5 5) voltage)
    )

    (else
    (write (0 0) port_ws)
    (if (match 1 input)
      (write (1 1) input)
      (write (1 1) output)
    )

    (write (2 2) consolid_iomode)
    (write (3 3) setup_hold_tmaxmin)
    (write (4 4) setup_hold_tmaxmin)
    (write (5 5) setup_hold_tmaxmin)
   )
   )
  )
 )
)

