
(filter {

d2d_tdi	i_neptune3g2_core/emu/U0_SC_EMUN3G2GS60_LOGIC/u0_dap/uDAPJTAGDP/uDAPJtagDpProtocol/jtagsir_reg[3]/D
d2d_tdi	i_neptune3g2_core/emu/U0_SC_EMUN3G2GS60_LOGIC/u0_dap/uDAPJTAGDP/uDAPJtagDpProtocol/jtagsdr_reg[34]/D
d2d_tdi	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/edt/top_level_edt_decompressor_i/segment3/lfsm_vec_reg_4_/SCAN
d2d_tdi	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/edt/top_level_edt_decompressor_i/segment3/lfsm_vec_reg_12_/SCAN
d2d_tdi	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/edt/top_level_edt_decompressor_i/segment3/lfsm_vec_reg_10_/SCAN
d2d_tdi	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/edt/top_level_edt_decompressor_i/segment3/lfsm_vec_reg_8_/SCAN
 clock	mcspi1_clk
d2d_clk26mi	mcspi1_somi
d2d_nrespwron	d2d_rtck
d2d_nrespwron	d2d_tdo
d2d_nrespwron	jtag_emu0
d2d_nrespwron	jtag_emu1
d2d_nrespwron	mcspi1_somi
d2d_nrespwron	sys_boot1
d2d_tck	d2d_rtck
d2d_tdi	d2d_tdo


d2d_tdi	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/bcm/U0_bcm_arch03/DRSTS_PBIST/status_reg_r_reg_31_/D
d2d_tdi	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/dftioctrl/DFT_IO_CTRL_DR/ctrl_reg_r_reg_842_/D

cam_d1	i_neptune3g2_core/cam/C3PICAMPDATA[3]
cam_d1	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/gpio4/U_asyncpath/U_IPSYNCHROEVENT_1/U0_IPSYNCHROEVENT_CAPT_0/a_capture_r_reg/CLK
cam_d1	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/gpio4/U_asyncpath/U_IPSYNCHROEVENT_1/U0_IPSYNCHROEVENT_CAPT_0/a_capture_r_reg/D
cam_d1	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/gpio4/U_asyncpath/U_IPSYNCHROEVENT_1/U1_IPSYNCHROEVENT_CAPT_0/a_capture_r_reg/CLK
cam_d1	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/gpio4/U_debouncepath/U_DEBOUNCE_1/gpiopinsi_s0_r_reg/D
cam_d1	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/gpio4/U_ocpintf/gpio_datain_nxt_r_reg_1_/D
cam_d1	i_neptune3g2_core/core/U0_SC_COREN3G2GS60/U0_SC_COREN3G2GS60_LOGIC/core/gpio4/U_syncpath/U_SYNCEDGE_1/gpioin_sync_s0r_reg/D

jtag_emu1	i_neptune3g2_core/emu/Diode_PIETBMBISTRSTL_TI_BUFFER_RING_PIETBMBISTRSTL/A
cam_d1	i_neptune3g2_core/dsp/EMUI[1]

})
