(severity_pos
 (error    0)
 (warning  1)
 (info     2)
 (unknown  3)
)

(header_header      Waiver Id Rule Alias Severity File Line Wt Message "Waiver Comment")

(waive_fields
 (waived     A1 )
 (rule       A3 )
 (severity   A5 )
 (file       A6 )
 (line       A7 )
 (message    A9 )
 (comment    A10)
)

; # NOT USED ANYMORE
; #                  Red  Blue Yellow Orange Violet
(waived_colorindex   3    5    6      46     13)


(waive_directory     SPYGLASS_WAIVER)

(waive_arg_list      severity message file  line  rule  comment)
(waive_command_line  {
// [<severity>] <message>
waive  -file_line "<file>" <line>  -rule <rule>}  { -comment "<comment>"})
