(format
 (link_cell           (bg_color light_blue2) (align center) (valign vcenter) (bottom 2) (bottom_color white) (left 1) (left_color white))
 (violink_cell        (bg_color light_red) (color white) (bold 1) (align center) (valign vcenter) (bottom 2) (bottom_color white) (left 1) (left_color white))
 (vcell               (bg_color light_red) (color white) (bold 1) (align center) (valign vcenter) (bottom 2) (bottom_color white) (left 1) (left_color white))
 (vcelldata           (bg_color red) (color white) (bold 1) (align center) (valign vcenter) (bottom 2) (bottom_color white) (left 1) (left_color white))
 (vcell_orange        (bg_color orange) (color black) (bold 1) (align center) (valign vcenter) (bottom 2) (bottom_color white) (left 1) (left_color white))
 (count               (bg_color number) (align center) (valign vcenter)
                     (top 1) (top_color white) (bottom 1) (bottom_color white) (left 1) (left_color white) (right 1) (right_color white))
 (ep_triplet          (bg_color light_green) (color black) (bold 1) (align center) (valign vcenter) (bottom 2) (bottom_color white) (left 1) (left_color black))

 (vfrequency          (bg_color light_blue2) (color black) (bold 1) (align center) (top 1) (top_color white) (bottom 1) (bottom_color white) (left 1) (left_color white))

 (clockedge_lrb      (bg_color white) (color black) (size 11) (bold 1) (align center)  (left 1) (right 1))
 (l_latencies        (bg_color beige) (color black) (size 11) (bold 1) (align center)  (right 1) (bottom 1) (bottom_color white))
 (r_latencies        (bg_color light_orange1) (color black) (size 11) (bold 1) (align center)  (right 1) (bottom 1) (bottom_color white))
 (pos_skew           (bg_color light_green) (color black) (size 11) (bold 1) (align center)  (right 1) (bottom 1) (bottom_color white))
 (neg_skew           (bg_color orange) (color black) (size 11) (bold 1) (align center)  (right 1) (bottom 1) (bottom_color white))
 (nofrequency        (bg_color purple) (color black) (size 11) (bold 1) (align center) (top 1) (top_color white) (bottom 1) (bottom_color white))
)

