(clockmatrix_sequence by_startpoint_clock by_endpoint_clock by_pathtype)
(eponsout_sequence   by_pathtype by_startpoint by_endpoint by_pathgroup by_mode by_corner by_iomode)
(filterout_sequence  by_pathtype by_mode by_corner by_iomode by_startpoint by_endpoint by_pathgroup)

(treeout_sequence    by_startpoint by_endpoint by_pathgroup)

(syncts_sequence      by_pathtype by_pathgroup by_startpoint_clock by_endpoint_clock)
(interface_1_sequence  by_interface)
(interface_2_sequence  by_pathtype by_iomode by_pathgroup by_startpoint_clock by_endpoint_clock)

(quick_dft_sequence  by_startpoint by_endpoint)

(defaultout_sequence by_pathtype)

(by_ports
  (input            group_by_port input)
  (output           group_by_port output)
)

(by_startpoint_clock (startpoint_clock group_by startpoint_clock (clock_aware 1) (verbose 0)))
(by_endpoint_clock   (endpoint_clock   group_by endpoint_clock   (clock_aware 1) (verbose 0)))

(by_startpoint       (startpoint       group_by startpoint ))
(by_endpoint         (endpoint         group_by endpoint   ))
(by_pathgroup        (pathgroup        group_by path_group ))
(by_mode             (mode:            group_by mode       ))
(by_corner           (corner           group_by corner     ))
(by_iomode           (iomode           group_by iomode     ))
(by_pathtype         (pathtype         group_by path_type  ))

(by_dataMD5          (data_path_md5    group_by data_path_md5))
(by_interface        (interface        group_byRE reportfile "\.([a-zA-Z\d_]+)\.\w+$"))
(by_arrow_pin        (arrow_pin        group_byRE first_arrow_point ".+/(\w+)"))


(_eponsout_global
  (vertical    0 2 4 6)
  (horizontal  0 2 4)
  (header
    Index
    Type
    "Start Point"
    "End Point"
    "Path Group"
    WNS
  )

  (xpad   2)
  (ypad   2)
)

;(by_portset         (porset             group_byportset   (set p1 p2 p3)    (set p4 p5 p6)  (set p7)))
