(action		dm_measures)
(variant        1)

(filter_sequence             mode iomode timing_segments corner)
(tck_filter_sequence         mode tck_iomode corner tck_timing_segments)
(clock_filter_sequence       mode iomode clock-timing_segments corner)

(maptable
 (clock-map 		dm_clock_paths)
 (DEFAULT		reportiming)
)

(mode	
  (functional 	   "mode =~ /^func/")
)

(iomode 
  (jtag  	   "iomode =~ /^io_mode[0-2]/")
)

(tck_iomode 
  (io_mode0  	   "iomode =~ /^io_mode0/")
  (io_mode1  	   "iomode =~ /^io_mode1/")
;  (io_mode2  	   "iomode =~ /^io_mode2/")
)

(timing_segments
  (A1-A2	"startpoint =~ /jtag_tdi/    && endpoint =~ /d2dn3gtdi/")
  (B1-B2	"startpoint =~ /jtag_tms/    && endpoint =~ /d2dn3gtms/")
  (E1-E2	"startpoint =~ /d2dn3gtdo/   && endpoint =~ /jtag_tdo/")
)

(tck_timing_segments
;  (F1F2	          "startpoint =~ /jtag_tck/    && endpoint =~ /i_omap2430c_core.mpu.armret_wrap_i.SCV2_ARM1136JF_ETK11_C0270_i.TCK/")
  (F11F12	  "startpoint =~ /jtag_tck/    && endpoint =~ /i_omap2430c_core.wkup.wkup.TSSPOMPUTCK/")
  (F13F14	  "startpoint =~ /i_omap2430c_core.wkup.wkup.TSSPOMPUTCK/  && endpoint =~ /i_omap2430c_core.mpu.armret_wrap_i.SCV2_ARM1136JF_ETK11_C0270_i.TCK/")
  (G1G2-LAUNCH	  "launch_clock_path_startnode  =~ /i_omap2430c_core.mpu.armret_wrap_i.SCV2_ARM1136JF_ETK11_C0270_i.RTCK/   && launch_clock_path_endnode =~ /jtag_rtck/")
  (G1G2-CAPTURE   "capture_clock_path_startnode =~ /i_omap2430c_core.mpu.armret_wrap_i.SCV2_ARM1136JF_ETK11_C0270_i.RTCK/   && capture_clock_path_endnode =~ /jtag_rtck/")
  (H1H2-LAUNCH    "launch_clock_path_startnode  =~ /jtag_tck/ && launch_clock_path_endnode  =~ /jtag_rtck/")
  (H1H1-CAPTURE   "capture_clock_path_startnode =~ /jtag_tck/ && capture_clock_path_endnode =~ /jtag_rtck/")
;  (Z1Z2           "startpoint =~ /jtag_tck/ && endpoint =~ /jtag_rtck/")
)

(clock-timing_segments
  (C1-C2	  "startnode =~ /jtag_tck/    && endnode =~ /d2dn3gtck/")
  (D1-D2	  "startnode =~ /d2dn3grtck/  && endnode =~ /jtag_rtck/")
)

(corner
 (1.4_QC_MIN	       "corner =~ /^1\.4_QC_MIN/")
 (1.4_QC_MAX	       "corner =~ /^1\.4_QC_MAX/")
 (QC_MAX	       "corner =~ /^QC_MAX/")
 (QC_MIN	       "corner =~ /^QC_MIN/")
 (VBOX_MIN             "corner =~ /^VBOX_MIN$/")
 (VBOX_MAX             "corner =~ /^VBOX_MAX$/")
 (BURNIN_MIN           "corner =~ /^BURNIN_MIN$/")
 (BURNIN_MAX           "corner =~ /^BURNIN_MAX$/")
 (1.05_QC_MIN	       "corner =~ /^1\.05_QC_MIN/")
 (1.05_QC_MAX_LT       "corner =~ /^1\.05_QC_MAX_LT/")
)


(corner-order   1.4_QC_MIN
                1.4_QC_MAX
                QC_MIN
                QC_MAX
                1.05_QC_MIN
                1.05_QC_MAX_LT
                VBOX_MIN
                VBOX_MAX
                BURNIN_MIN
                BURNIN_MAX
)

(what-to-look
  (F1F2	          propagation_delay)
  (F11F12	  propagation_delay)
  (F13F14	  propagation_delay)
  (G1G2-LAUNCH	  launch_clock_path_delta)
  (G1G2-CAPTURE   capture_clock_path_delta)
  (H1H2-LAUNCH    launch_clock_path_delta)
  (H1H1-CAPTURE   capture_clock_path_delta)
  (Z1Z2           propagation_delay)
)

(dmsegment_name_map
  (A1-A2	  JTAGTDI_2_D2DN3GTDI)
  (B1-B2	  JTAGTMS_2_D2DN3GTMS)
  (E1-E2	  D2DN3GTDO_2_JTAGTDO)
  (C1-C2	  JTAGTCK_2_D2DN3GTCK)
  (D1-D2	  D2DN3GRTCK_2_JTAGRTCK)
  (F11F12	  JTAGTCK_2_TSSPOMPUTCK)
  (F13F14	  TSSPOMPUTCK_2_ARMTCK)
  (G1G2-LAUNCH	  ARMRTCK_2_JTAGRTCK_L)
  (G1G2-CAPTURE   ARMRTCK_2_JTAGRTCK_C)
  (H1H2-LAUNCH    JTAG_TCK2RTCK_L)
  (H1H1-CAPTURE   JTAG_TCK2RTCK_C)
)
