(default_opt
 (rpt_consolidate
  (path-filter	"\/func_.*\/"	)
  (file-filter	"viols_.*_verb"	)
  (2430c	 1)
  (with-path	 1)
  (nodes-extract 0)
  (csplit	 0)
 )
 
 (regrestatus
  (merge    	1)
  (md5sum    	1)
 )
 
 (tcfix (reference	1))
)

(simple_opt 
 (rpt_consolidate 
  (xls   	 1) 
  (2430c 	 1) 
  (with-path	 1) 
  (nodes-extract 1)
  (regrestatus   1)
  (csplit        1)
 )
 
 (regrestatus	  (merge 1) (md5sum 1))
 
 (tcfix	  (reference  1))
)

;(gui_file	"[seto://env/CONF_DIR]/tcflow.tk")

(interface	jtag)
(interface_filter
 (jtag	        {
                 mode   =~ /^func_/       &&
		 iomode =~ /io_mode[0-2]/ && 
		 (startpoint_clock =~ /jtag|rtck|tck|EFC_SYS_CLK|EFC_FCLK|EFC_CLK/ || endpoint_clock =~ /jtag|rtck|tck|EFC_SYS_CLK|EFC_FCLK|EFC_CLK/)
		}
 )  

 (dft_not_tft	"startpoint_clock !~ /jtag|rtck|tck/ && endpoint_clock !~ /jtag|rtck|tck/")  
)



(STANLOF_WDIR	  seto://stan_old/STANLOF_WDIR)

(qc_scale_file	"[seto://env/CONF_DIR]/hold_scale_factors_to_qcmin.conf")
(qc_target         QC_MAX)

(regresss_directory_root_default	/db/omap2430c_es2_sta/reports)

(scale_2_qcmax)

;(uniquify_path)
;(noexecution)
;(noxls)
;(noregrestatus)
;(notcfix)
;(nostan)

(reportdirectory_regexp    "^/db/omap2430c_es(?:2|1p)_sta(?:-si)?/reports/handoff")

(regression_directory_list   /sim/neptune3g2_sta-ocv/reports
			     /sim/neptune3g2_sta-si/reports
			     /db/neptune3g2_sta/reports
			     /db/neptune3g2_sta1/jp
			     /db/neptune3g2_sta-si/reports
			     /db/omap2430c_es2_sta/reports 
                             /db/omap2430c_es1p_sta-si/reports 
			     /db/omap2430c_es2_sta-si/reports 
			     /db/omap2430c_es1p_sta/reports
)
