;(action tssio)

(maptable
 (DEFAULT	reportiming)
)

(filter_sequence mode interface direction port clock iomode corner)

(port
 (port  group_by_port both)
)

(clock
 (clock  group_by_ioclock auto)
)

(mode	
  (functional "mode =~ /^func/")
)

(corner
 (1.4	"corner =~ /^1\.4/")
 (1.3	"corner =~ /^QC/")
 (1.05	"corner =~ /^1\.05/")
)

(interface
 (camera  "reportfile =~ /CAM.*\.rpt$/")
 (sdi     "reportfile =~ /SDI.*\.rpt$/")
 (mcbsp   "reportfile =~ /MCBSP.*\.rpt$/")
)

(direction
  (input    "startpoint !~ /\// && endpoint =~ /\//")
  (output   "startpoint =~ /\// && endpoint !~ /\//")
)


(iomode 
  (iomode0 "iomode =~ /^io_mode0/")
  (iomode1 "iomode =~ /^io_mode1/")
  (iomode2 "iomode =~ /^io_mode2/")
  (iomode3 "iomode =~ /^io_mode3/")
  (iomode4 "iomode =~ /^io_mode4/")
  (iomode5 "iomode =~ /^io_mode5/")
)


(toindex
 (corner
  (1.4	  0)
  (1.3	  1)
  (1.05	  2)
 )

 (direction
  (input   0)
  (output  1)
 )

 (maxmin
  (setup   0)
  (hold    1)
 )

 (tssta
  (freq    0)
  (halfull 1)
  (tss     2)
  (sta     3)
 )
)

(header_1stpart   interface iomode port  reference_clock)
(header_varpart   frequency cycle_type setupTSS setupSTA + cycle_type holdTSS holdSTA frequency cycle_type tmaxTSS tmaxSTA + cycle_type tminTSS tminSTA)
