(keywords
 entity begin end architecture component port generic generate if else elsif then character 
 std_logic std_logic_vector read read_line write write_line assert report for while case package 
 body ieee is and or constant use library std textio all type record array in out inout access 
 variable line string to downto integer boolean function procedure return loop null nul xor xnor 
 range natural file open shared severity rising_edge falling_edge others exit next when process 
 map configuration "'(?:length|pos)" new true false work wait
)
