(context_clause seto://fsmgen/context_clause)
(dirmap
 (input  IN)
 (output OUT)
 (inout  INOUT)
)

(_prog  xif)
; The !! is just a trick to force an array ref (minimum 2 values)
(regex  !! .)
(sort    0)
(debug   0)
(show    0)
(change  0)
(arch    0)
(xcel    0)

; The !! is just a trick to force an array ref (minimum 2 values)
(exclude !! _primary\.vhd)

(include !! .)

(direction_map
  (in    INPUT)
  (out   OUTPUT)
  (inout INOUT)
)

; Sorting rules
(mif_sort    by_port by_direction by_msi by_lsi by_release)
(by_port       (port       group_by port))
(by_direction  (direction  group_by direction))
(by_msi        (msi        group_by msi))
(by_lsi        (lsi        group_by lsi))
(by_release    (release group_byRE file "release_(\d+_\d+)"))

(maptable (DEFAULT mif))

; Verilog Reserved Keywords
(vkw  always end ifnone or rpmos tranif1 and endcase initial output rtran 
      tri assign endmodule inout parameter rtranif0 tri0 begin endfunction 
      input pmos rtranif1 tri1 buf endprimitive integer posedge scalared 
      triand bufif0 endspecify join primitive small trior bufif1 endtable 
      large pull0 specify trireg case endtask macromodule pull1 specparam 
      vectored casex event medium pullup strong0 wait casez for module pulldown 
      strong1 wand cmos force nand rcmos supply0 weak0 deassign forever negedge 
      real supply1 weak1 default for nmos realtime table while defparam function 
      nor reg task wire disable highz0 not release time wor edge highz1 notif0 repeat 
      tran xnor else if notif1 rnmos tranif0 xor
)

; Verilog Primitives
(vp and buf nmos tran pullup nand not pmos tranif0 pulldown
    nor bufif0 cmos tranif1 or bufif1 rnmos rtran
    xor notif0 rpmos rtranif0 xnor notif1 rcmos rtranif1 
)

; Don't change the following unless you exactly know what you're doing
(portinfo_map
  (0  direction)
  (1  msi)
  (2  lsi)
  (field (0 0) (1 2) (2 3))
)
