#!/usr/bin/env python3
"""
Create a clean/sorted EBNF grammar from a normalized EBNF input.
"""

from __future__ import annotations

import argparse
import re
from collections import OrderedDict
from pathlib import Path


RULE_HEAD_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*::=\s*$")


def parse_rules(text: str) -> OrderedDict[str, str]:
    rules = OrderedDict()
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        m = RULE_HEAD_RE.match(lines[i])
        if not m:
            i += 1
            continue
        name = m.group(1)
        i += 1
        parts = []
        while i < len(lines):
            line = lines[i].strip()
            if not line:
                i += 1
                continue
            if RULE_HEAD_RE.match(lines[i]):
                break
            if line.endswith(";"):
                parts.append(line[:-1].strip())
                i += 1
                break
            parts.append(line)
            i += 1
        definition = re.sub(r"\s+", " ", " ".join(parts)).strip()
        if definition:
            rules[name] = definition
    return rules


def main() -> int:
    ap = argparse.ArgumentParser(description="Create a clean EBNF grammar from normalized input.")
    ap.add_argument("--input-ebnf", required=True, help="Input EBNF path")
    ap.add_argument("--output-ebnf", required=True, help="Output clean EBNF path")
    args = ap.parse_args()

    inp = Path(args.input_ebnf).expanduser().resolve()
    out = Path(args.output_ebnf).expanduser().resolve()
    if not inp.is_file():
        raise SystemExit(f"error: input EBNF not found: {inp}")

    rules = parse_rules(inp.read_text(encoding="utf-8", errors="replace"))
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = []
    lines.append("# Clean grammar generated by create_clean_grammar.py")
    lines.append("")
    for name in sorted(rules.keys()):
        lines.append(f"{name} ::=")
        lines.append(f"    {rules[name]} ;")
        lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")

    print(f"input_ebnf: {inp}")
    print(f"output_ebnf: {out}")
    print(f"rule_count: {len(rules)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
