#!/usr/bin/env perl
use strict;
use warnings;
use Data::Dumper;
use FindBin qw($RealBin);

# Add the tracked Perl parser core directory to @INC
use lib "$RealBin/../perl";
use LinkedSpec;

# Configuration for generation
my $MAX_RECURSION_DEPTH = 3;
my $MAX_QUANTIFIER_COUNT = 4;
my $MAX_RULES_PER_FILE = 10;

# Load ebnf.spec and create the EBNF parser
print STDERR "Loading ebnf.spec...\n";
my $ebnf_spec_content = do {
    open my $fh, '<', "$RealBin/../specs/ebnf.spec" or die "Cannot read ebnf.spec: $!";
    local $/;
    <$fh>;
};

print STDERR "Creating EBNF parser...\n";
my $ebnf_parser = LinkedSpec::Get(\$ebnf_spec_content);

# Test the parser works
my $test_ebnf = "rule := 'test' -> \$1\n";
print STDERR "Testing parser with: $test_ebnf";
my $result = eval { $ebnf_parser->(\$test_ebnf) };
if ($@) {
    die "EBNF parser failed: $@";
}
print STDERR "Parser test successful!\n";

# Now we need to examine the internal structure
# Let's look at what LinkedSpec.pm creates internally
print STDERR "Examining LinkedSpec internal structures...\n";

# We need to modify LinkedSpec.pm or create a way to access its internal grammar data
# For now, let's create a simple rule-based generator based on ebnf.spec structure

sub generate_ebnf_file {
    my ($num_rules, $filename) = @_;
    
    my @generated_rules = ();
    my @rule_names = ();
    
    # Generate rule names first
    for my $i (1..$num_rules) {
        my $rule_name = generate_rule_name();
        push @rule_names, $rule_name;
    }
    
    # Generate rules
    for my $i (0..$num_rules-1) {
        my $rule_name = $rule_names[$i];
        my $rule_def = generate_rule_definition(\@rule_names, 0);
        push @generated_rules, "$rule_name := $rule_def";
    }
    
    # Write to file
    open my $fh, '>', $filename or die "Cannot write to $filename: $!";
    print $fh "# Generated EBNF file for testing\n";
    print $fh "# Generated by ebnf_generator.pl\n\n";
    print $fh join("\n", @generated_rules) . "\n";
    close $fh;
    
    print "Generated $filename with " . scalar(@generated_rules) . " rules\n";
}

sub generate_rule_name {
    my @prefixes = qw(expr stmt item list element token atom value);
    my @suffixes = qw(def rule part comp elem node);
    
    my $prefix = $prefixes[rand @prefixes];
    my $suffix = $suffixes[rand @suffixes];
    my $num = int(rand(99)) + 1;
    
    return "${prefix}_${suffix}_${num}";
}

sub generate_rule_definition {
    my ($rule_names, $depth) = @_;
    
    # Limit recursion depth
    return generate_terminal() if $depth >= $MAX_RECURSION_DEPTH;
    
    # Choose what type of rule to generate
    my $choice = rand();
    
    if ($choice < 0.4) {
        # Simple terminal
        return generate_terminal();
    } elsif ($choice < 0.6) {
        # OR rule with multiple alternatives
        return generate_or_rule($rule_names, $depth);
    } elsif ($choice < 0.8) {
        # Sequence rule
        return generate_sequence_rule($rule_names, $depth);
    } elsif ($choice < 0.9) {
        # Quantified rule
        return generate_quantified_rule($rule_names, $depth);
    } else {
        # Rule with return annotation
        return generate_rule_with_return($rule_names, $depth);
    }
}

sub generate_terminal {
    # Use only alphanumeric terminals to avoid function name issues
    my @terminals = (
        "'start'", "'end'", "'begin'", "'finish'", 
        "'if'", "'then'", "'else'", "'while'", "'for'", "'do'",
        "'true'", "'false'", "'null'", "'void'", "'int'", "'string'",
        "'class'", "'function'", "'return'", "'var'", "'const'", "'let'"
    );
    
    return $terminals[rand @terminals];
}

sub generate_or_rule {
    my ($rule_names, $depth) = @_;
    
    my $num_alts = int(rand(3)) + 2; # 2-4 alternatives
    my @alternatives = ();
    
    for my $i (1..$num_alts) {
        push @alternatives, generate_rule_definition($rule_names, $depth + 1);
    }
    
    return join(' | ', @alternatives);
}

sub generate_sequence_rule {
    my ($rule_names, $depth) = @_;
    
    my $num_elements = int(rand(3)) + 2; # 2-4 elements
    my @elements = ();
    
    for my $i (1..$num_elements) {
        if (rand() < 0.6 && @$rule_names > 0) {
            # Reference another rule (higher probability)
            my $rule_ref = $rule_names->[rand @$rule_names];
            push @elements, $rule_ref;
        } else {
            # Use simple terminals for the rest
            push @elements, generate_terminal();
        }
    }
    
    return join(' ', @elements);
}

sub generate_quantified_rule {
    my ($rule_names, $depth) = @_;
    
    # Generate a simple base (avoid nested quantifiers)
    my $base;
    if (rand() < 0.5 && @$rule_names > 0) {
        $base = $rule_names->[rand @$rule_names];
    } else {
        $base = generate_terminal();
    }
    
    my @quantifiers = ('?', '*', '+');
    my $quantifier = $quantifiers[rand @quantifiers];
    
    return "$base$quantifier";
}

sub generate_rule_with_return {
    my ($rule_names, $depth) = @_;
    
    # Generate a simple base to avoid double return annotations
    my $base;
    if (rand() < 0.4 && @$rule_names > 0) {
        $base = $rule_names->[rand @$rule_names];
    } else {
        $base = generate_terminal();
    }
    
    my $return_annotation = generate_return_annotation();
    
    return "$base -> $return_annotation";
}

sub generate_return_annotation {
    my $choice = rand();
    
    if ($choice < 0.4) {
        # Scalar return
        my @scalars = ('$1', '$2', '$3', '"literal"', "'value'");
        return $scalars[rand @scalars];
    } elsif ($choice < 0.7) {
        # Array return  
        my @arrays = ('[$1*]', '[$1, $2]', '[$1, $2, $3]', '[$2*]');
        return $arrays[rand @arrays];
    } else {
        # Object return
        my @objects = (
            '{type: $1}',
            '{value: $1, type: "node"}', 
            '{left: $1, right: $2}',
            '{items: [$1*]}',
            '{name: $1, args: [$2*]}'
        );
        return $objects[rand @objects];
    }
}

# Generate multiple test files
print "Starting EBNF file generation...\n";

for my $i (1..5) {
    my $num_rules = int(rand(8)) + 3; # 3-10 rules per file
    my $filename = "generated_test_${i}.ebnf";
    generate_ebnf_file($num_rules, $filename);
}

print "EBNF generation complete!\n";
