#!/usr/bin/env bash
# ENGINE-UNIVERSAL-SERVICES.19 slice 1 — is the 99 747-byte gap the EMBEDDED `-o` PATH?
#
# `.19` records two narrow-admission SystemVerilog parsers that should have been the same artifact:
#
#   4330ff8e…  131 642 655 B   tracked pre-flip, generated by `make` (cwd `rust/`)
#   dae09343…  131 542 908 B   session #232 ad-hoc re-derivation      (cwd repo root)
#                --------------
#                     99 747 B  unaccounted for
#
# The leaf lists two hypotheses — (a) `.17` slice 9's diff perturbed SV codegen, (b) the git-ignored
# input `generated/systemverilog.json` moved. ⛔ It lists neither the mechanism this probe tests,
# because that mechanism was not discovered until TWO SESSIONS LATER, by `.20` slice 3
# (`PGEN-ENGINE-UNIVERSAL-SERVICES-0042`): **the generated SystemVerilog parser embeds its own `-o`
# path once per rule-entry site**, so a longer `-o` spelling makes a byte-identical parser bigger.
#
#   make          `-o ../generated/systemverilog_parser.rs`   36 chars
#   ad-hoc        `-o generated/systemverilog_parser.rs`      33 chars
#                                                             -- 3 chars
#
# The narrow arm carries 33 249 such sites, and 33 249 × 3 = 99 747 — the gap, exactly.
#
# ⛔ ARITHMETIC AGREEMENT IS AN ILLUSTRATION, NOT A TEST (`docs/CLAIM_VERIFICATION.md` §3 leg 2): a
# byte COUNT that matches is equally consistent with "the path explains every byte" and with "the
# path explains 99 747 bytes and something else explains 0 net". Arm 3 separates them by NORMALISING
# the long spelling to the short one and demanding **byte-identity**, and arm 5 proves that
# comparison can go RED.
#
# ⛔ THIS PROBE NEVER TOUCHES `generated/systemverilog_parser.rs`. It builds a mimic tree
#    <work>/root/{generated,rust} so the two `-o` strings are byte-identical to the real
#    invocations while the shipped artifact is left alone. Nothing here writes outside <work>.
#
# HOW:  bash docs/tasks/artifacts/engine_universal_services/es19_path_embedding/probe.sh
#       PGEN_ES19_KEEP=1 …   keep the four 131 MB parsers instead of deleting them
# COST: 4 SystemVerilog codegen runs, ~26 s each (~2 min), ~525 MB peak under rust/target/.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../.." && pwd)"
cd "$ROOT"

PIPELINE="$ROOT/rust/target/debug/ast_pipeline"
SV_JSON="$ROOT/generated/systemverilog.json"
WORK="$ROOT/rust/target/es19_path_embedding"

# The two spellings under test, and the recorded pair they explain.
LONG_REL="../generated/systemverilog_parser.rs"          # 36 chars — what `rust/Makefile` passes
SHORT_REL="generated/systemverilog_parser.rs"            # 33 chars — what the ad-hoc run passed
RECORDED_LONG_BYTES=131642655                            # 4330ff8e… tracked pre-flip
RECORDED_SHORT_BYTES=131542908                           # dae09343… session #232 re-derivation
RECORDED_GAP=99747

fails=0
pass() { printf '  ✓ %s\n' "$1"; }
fail() { printf '  ✗ %s\n' "$1" >&2; fails=$((fails + 1)); }

need() { [ -e "$1" ] || { printf 'es19-probe: missing %s\n' "$1" >&2; exit 2; }; }
need "$PIPELINE"
need "$SV_JSON"

# The narrow lever is a MEASUREMENT switch (`.17` slice 9); a parser built this way rejects
# LRM-legal SystemVerilog and is never a deliverable. It is the policy both recorded artifacts used.
LEVER=(--generate-parser --eliminate-left-recursion --indirect-lr-admit-starvation-safe-only)

# gen <cwd> <-o spelling> <input spelling> <keep-as>
gen() {
  local cwd="$1" out="$2" input="$3" keep="$4"
  ( cd "$cwd" && "$PIPELINE" "$input" "${LEVER[@]}" -o "$out" ) >/dev/null 2>&1 \
    || { printf 'es19-probe: codegen FAILED (cwd=%s -o=%s)\n' "$cwd" "$out" >&2; exit 2; }
  mv "$WORK/root/generated/systemverilog_parser.rs" "$keep"
}

sha() { shasum -a 256 "$1" | cut -d' ' -f1; }
size() { wc -c < "$1" | tr -d ' '; }

rm -rf "$WORK"
mkdir -p "$WORK/root/generated" "$WORK/root/rust"

printf '\nES19-PATH-EMBEDDING: is the 99 747-byte gap the embedded -o path?\n'
printf 'pipeline : %s\n' "$(cd "$ROOT" && git log -1 --format=%h)"
printf 'input    : %s (%s bytes)\n\n' "generated/systemverilog.json" "$(size "$SV_JSON")"

# ── generate the four arms ────────────────────────────────────────────────────────────────────────
# A1/A2 reproduce make's invocation byte-for-byte: cwd `<mimic>/rust`, `-o ../generated/…`.
gen "$WORK/root/rust"  "$LONG_REL"  "$SV_JSON" "$WORK/a1_long.rs"
gen "$WORK/root/rust"  "$LONG_REL"  "$SV_JSON" "$WORK/a2_long.rs"
# B1 reproduces the ad-hoc invocation: cwd `<mimic>`, `-o generated/…`.
gen "$WORK/root"       "$SHORT_REL" "$SV_JSON" "$WORK/b1_short.rs"
# B2 is B1 with the INPUT named by a different spelling — the competing "the input path is embedded
# too" hypothesis, tested rather than assumed.
gen "$WORK/root"       "$SHORT_REL" "../../../../generated/systemverilog.json" "$WORK/b2_short_relinput.rs"

A1_SHA=$(sha "$WORK/a1_long.rs");  A1_SZ=$(size "$WORK/a1_long.rs")
A2_SHA=$(sha "$WORK/a2_long.rs");  A2_SZ=$(size "$WORK/a2_long.rs")
B1_SHA=$(sha "$WORK/b1_short.rs"); B1_SZ=$(size "$WORK/b1_short.rs")
B2_SHA=$(sha "$WORK/b2_short_relinput.rs")

# ⛔ OCCURRENCES, not lines-with-a-match, and FIXED-string: `grep -c` counts LINES (two sites on one
# line would undercount) and an unanchored `.` in the pattern is a regex wildcard. Both spellings are
# one-per-line today, which is a measurement, not something to rely on.
SITES=$(grep -oF "$LONG_REL" "$WORK/a1_long.rs" | wc -l | tr -d ' ')
SITES_SHORT=$(grep -oF "$SHORT_REL" "$WORK/b1_short.rs" | wc -l | tr -d ' ')

printf 'arm A (make spelling, %2d chars)  %s  %s\n' "${#LONG_REL}"  "$A1_SZ" "$A1_SHA"
printf 'arm A (repeat)                    %s  %s\n'                 "$A2_SZ" "$A2_SHA"
printf 'arm B (ad-hoc spelling, %2d chars) %s  %s\n' "${#SHORT_REL}" "$B1_SZ" "$B1_SHA"
printf 'path sites: %s (long arm) / %s (short arm)\n\n' "$SITES" "$SITES_SHORT"

# ── ARM 1 — DETERMINISM (`.19` acceptance (a)) ────────────────────────────────────────────────────
printf 'ARM 1  determinism — acceptance (a)\n'
if [ "$A1_SHA" = "$A2_SHA" ]; then
  pass "two runs of one binary at one spelling are byte-identical ($A1_SHA)"
else
  fail "codegen is NON-DETERMINISTIC: $A1_SHA vs $A2_SHA — the investigation ends here"
fi

# ── ARM 2 — the gap is 3 bytes per site, and that reproduces the RECORDED gap ─────────────────────
printf 'ARM 2  byte arithmetic\n'
GAP=$((A1_SZ - B1_SZ))
PREDICTED=$((SITES * (${#LONG_REL} - ${#SHORT_REL})))
[ "$GAP" = "$PREDICTED" ] \
  && pass "measured gap $GAP == sites($SITES) × Δchars(3) = $PREDICTED" \
  || fail "measured gap $GAP != sites($SITES) × Δchars(3) = $PREDICTED"
[ "$GAP" = "$RECORDED_GAP" ] \
  && pass "and it EQUALS the gap .19 recorded between 4330ff8e… and dae09343… ($RECORDED_GAP)" \
  || fail "gap $GAP != the recorded $RECORDED_GAP"
[ "$SITES" = "$SITES_SHORT" ] \
  && pass "both spellings carry the same site count — the count is a property of the grammar" \
  || fail "site count differs across spellings: $SITES vs $SITES_SHORT"

# ── ARM 3 — NORMALISED IDENTITY: the path is not merely the right COUNT of bytes ──────────────────
printf 'ARM 3  normalised identity (the falsification leg)\n'
LC_ALL=C sed "s|${LONG_REL//./\\.}|${SHORT_REL}|g" "$WORK/a1_long.rs" > "$WORK/a1_normalised.rs"
NORM_SHA=$(sha "$WORK/a1_normalised.rs")
if [ "$NORM_SHA" = "$B1_SHA" ]; then
  pass "arm A with its -o spelling rewritten to arm B's is BYTE-IDENTICAL to arm B ($NORM_SHA)"
  pass "⇒ the -o path is the ONLY difference between the two arms — not merely 99 747 bytes' worth"
else
  fail "normalised arm A ($NORM_SHA) != arm B ($B1_SHA) — something OTHER than the path also moved"
fi

# ── ARM 4 — the INPUT path is not embedded (a competing hypothesis, tested) ───────────────────────
printf 'ARM 4  input-path independence\n'
[ "$B1_SHA" = "$B2_SHA" ] \
  && pass "naming the input JSON two different ways yields a byte-identical parser" \
  || fail "the input spelling changed the artifact: $B1_SHA vs $B2_SHA"

# ── ARM 5 — RED CONTROL: prove arm 3's comparison can FAIL ────────────────────────────────────────
# A control never observed failing is not known to work (`docs/CLAIM_VERIFICATION.md` §3 leg 2).
# Normalise to a spelling that is one character LONGER than arm B's and demand a MISMATCH.
printf 'ARM 5  RED control — arm 3 must be able to fail\n'
LC_ALL=C sed "s|${LONG_REL//./\\.}|x${SHORT_REL}|g" "$WORK/a1_long.rs" > "$WORK/a1_wrongnorm.rs"
WRONG_SHA=$(sha "$WORK/a1_wrongnorm.rs")
if [ "$WRONG_SHA" != "$B1_SHA" ]; then
  pass "a deliberately WRONG normalisation is refused (RED as designed)"
else
  fail "the wrong normalisation MATCHED — arm 3 cannot distinguish anything and proves nothing"
fi

# ── ARM 6 — the RESIDUAL against the two recorded artifacts, reported not hidden ──────────────────
# Today's binary + today's JSON is not session #232's binary + session #232's JSON, so a byte-for-byte
# replay of the recorded pair is not expected. What IS expected — and checked — is that the residual
# is the SAME CONSTANT at both spellings: a per-site path effect is orthogonal to everything else.
printf 'ARM 6  residual vs the recorded pair (reported, not hidden)\n'
RES_LONG=$((A1_SZ - RECORDED_LONG_BYTES))
RES_SHORT=$((B1_SZ - RECORDED_SHORT_BYTES))
printf '  residual vs 4330ff8e… : %+d bytes\n  residual vs dae09343… : %+d bytes\n' "$RES_LONG" "$RES_SHORT"
if [ "$RES_LONG" = "$RES_SHORT" ]; then
  pass "the residual is the SAME at both spellings ⇒ orthogonal to the path effect"
else
  fail "residual differs by spelling ($RES_LONG vs $RES_SHORT) — the path model is incomplete"
fi
[ "$RES_LONG" = 0 ] \
  && pass "residual is ZERO — today's narrow arm replays the recorded pair exactly" \
  || printf '  ⚠️  residual is NOT zero: %+d bytes of SV codegen moved between session #232 and today,\n     at BOTH spellings, independent of this leaf'"'"'s question. Owned by .19 slice 2.\n' "$RES_LONG"

# ── report ────────────────────────────────────────────────────────────────────────────────────────
printf '\n'
if [ "$fails" -eq 0 ]; then
  printf 'ES19-PATH-EMBEDDING: ALL ARMS PASS (6 arms, 1 of them RED-by-design)\n'
else
  printf 'ES19-PATH-EMBEDDING: %d ARM(S) FAILED\n' "$fails" >&2
fi

if [ "${PGEN_ES19_KEEP:-0}" != "1" ]; then
  rm -f "$WORK"/*.rs "$WORK"/root/generated/*.json
  printf '(the four 131 MB parsers were deleted; PGEN_ES19_KEEP=1 keeps them)\n'
fi

exit "$fails"
