# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded stapack 1.0 [list source [file join $dir get_fanx.tcl]]\n[list source [file join $dir get_primary_clocks.tcl]]\n[list source [file join $dir write_iocsv.tcl]]\n[list source [file join $dir get_c2pcon.tcl]]\n[list source [file join $dir get_ctinfo.tcl]]\n[list source [file join $dir get_tpoints.tcl]]\n[list source [file join $dir is_gsx0_xyz.tcl]]\n[list source [file join $dir get_options.tcl]]\n[list source [file join $dir report_tia.tcl]]\n[list source [file join $dir check_iotimings_clocks.tcl]]\n[list source [file join $dir object.tcl]]\n[list source [file join $dir perlike.tcl]]\n[list source [file join $dir cross_talk.tcl]]\n[list source [file join $dir is_xy_pin.tcl]]\n[list source [file join $dir go_thru.tcl]]\n[list source [file join $dir get_xobj.tcl]]\n[list source [file join $dir write_clockinfo.tcl]]\n[list source [file join $dir get_fxy.tcl]]\n[list source [file join $dir get_shviolators.tcl]]\n[list source [file join $dir get_paths.tcl]]\n[list source [file join $dir get_gsx0_xyz.tcl]]\n[list source [file join $dir get_tpinfo.tcl]]\n[list source [file join $dir get_iotimings.tcl]]
